def error(message: str):
  print(f'ERROR: {message}')
  exit(1)
